# Generated by Django 5.2 on 2025-05-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_pettycash'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycash',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
