# Generated by Django 5.2 on 2025-05-16 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_pettycash_isapproved'),
    ]

    operations = [
        migrations.AddField(
            model_name='pettycash',
            name='control_number',
            field=models.CharField(blank=True, max_length=8, unique=True),
        ),
    ]
