# Generated by Django 5.2 on 2025-05-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_pettycash_control_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pettycash',
            name='control_number',
            field=models.CharField(blank=True, max_length=11, unique=True),
        ),
    ]
